[project]
name = "ecommerce-dbt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dbt-duckdb>=1.10.0",
    "duckdb>=1.4.3",
]
